/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export type $Read<T> = {
    readonly $read: T;
};
export type $Write<T> = {
    readonly $write: T;
};
export type Readable<T> = T extends $Write<any> ? never : T extends $Read<infer U> ? Readable<U> : T extends (infer E)[] ? Readable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Write<any> ? never : K]: Readable<T[K]>;
} : T;
export type Writable<T> = T extends $Read<any> ? never : T extends $Write<infer U> ? Writable<U> : T extends (infer E)[] ? Writable<E>[] : T extends object ? {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? never : K]: Writable<T[K]>;
} & {
    [K in keyof T as NonNullable<T[K]> extends $Read<any> ? K : never]?: never;
} : T;
export interface paths {
    readonly "/auth/login": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 创建管理员 Session */
        readonly post: operations["login"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/logout": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 销毁当前管理员 Session */
        readonly post: operations["logout"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/auth/me": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取当前管理员和 CSRF Token */
        readonly get: operations["getCurrentAdmin"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 分页读取 Tunnel */
        readonly get: operations["listTunnels"];
        readonly put?: never;
        /** 创建 Tunnel 并签发第一代 Connection Token */
        readonly post: operations["createTunnel"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        /** 读取单个 Tunnel */
        readonly get: operations["getTunnel"];
        readonly put?: never;
        readonly post?: never;
        /**
         * 删除没有 Service 引用的 Tunnel
         * @description 不级联 Service 或 Route；存在引用时返回 TUNNEL_IN_USE。
         */
        readonly delete: operations["deleteTunnel"];
        readonly options?: never;
        readonly head?: never;
        /** 以 JSON Merge Patch 修改 Tunnel 名称 */
        readonly patch: operations["updateTunnel"];
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}/connectors": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        /**
         * 分页读取仍有 Current Control Session 的 Connector
         * @description 断连或心跳过期后不返回，也不伪造 OFFLINE 状态。
         */
        readonly get: operations["listTunnelConnectors"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}/token": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        /** 审计后返回当前 ACTIVE Connection Token */
        readonly get: operations["revealTunnelToken"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}/token/rotate": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 签发下一代 Token；既有 Session 保持在线 */
        readonly post: operations["rotateTunnelToken"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}/token/revoke": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 撤销当前 Token 的新认证但不撤销 Tunnel */
        readonly post: operations["revokeTunnelToken"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/tunnels/{tunnel_id}/revoke": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 撤销 Tunnel、全部 Token 与运行时访问 */
        readonly post: operations["revokeTunnel"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/services": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 分页读取一个 Tunnel 下的 Service */
        readonly get: operations["listServices"];
        readonly put?: never;
        /**
         * 在指定 Tunnel 下创建 Service
         * @description If-Match 必须是父 Tunnel 的当前强 ETag。
         */
        readonly post: operations["createService"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/services/{service_id}": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        /** 读取单个 Service */
        readonly get: operations["getService"];
        readonly put?: never;
        readonly post?: never;
        /**
         * 删除 Service 及其唯一 Public Exposure
         * @description Service 与 Exposure 在同一事务内删除，不留下 Route 引用。
         */
        readonly delete: operations["deleteService"];
        readonly options?: never;
        readonly head?: never;
        /**
         * 以 JSON Merge Patch 修改 Service
         * @description If-Match 是绑定 Service Version 与 Tunnel Version 的强不透明 ETag。omitted 表示
         *     不修改；health/exposure 的 null 表示禁用或移除；其他 null 返回 VALIDATION_FAILED。
         */
        readonly patch: operations["updateService"];
        readonly trace?: never;
    };
    readonly "/services/{service_id}/enable": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 启用 Service */
        readonly post: operations["enableService"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/services/{service_id}/disable": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly get?: never;
        readonly put?: never;
        /** 禁用 Service */
        readonly post: operations["disableService"];
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/dashboard": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取 Server 权威状态汇总 */
        readonly get: operations["getDashboard"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/info": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取 Server 构建与运行信息 */
        readonly get: operations["getSystemInfo"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/health": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /** 读取已认证的管理面健康状态 */
        readonly get: operations["getSystemHealth"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/system/config": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 读取安全的 Server 有效配置投影
         * @description 不返回路径、Private Key、Token、Secret 或完整内部 Config。
         */
        readonly get: operations["getSystemConfig"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/security-audit-events": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 只读查询持久化 Security Audit Event
         * @description 按 (occurred_at,event_id) 倒序；游标绑定全部筛选条件；Digest 是 32-byte 值的
         *     小写十六进制文本。本资源没有任何 Mutation endpoint。
         */
        readonly get: operations["listSecurityAuditEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
    readonly "/security-audit-events/export": {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        /**
         * 流式导出持久化 Security Audit Event
         * @description 复用列表筛选语义。Server 在响应开始前固定 (occurred_at,event_id) 上界，
         *     随后按倒序 keyset 有界分页并逐行输出完整 SecurityAuditEvent JSON；并发追加
         *     不进入本次导出。连接取消或写失败会立即终止，客户端不得把中断响应视为完整导出。
         */
        readonly get: operations["exportSecurityAuditEvents"];
        readonly put?: never;
        readonly post?: never;
        readonly delete?: never;
        readonly options?: never;
        readonly head?: never;
        readonly patch?: never;
        readonly trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * Format: date-time
         * @description RFC 3339 UTC `Z` 时间戳。
         */
        readonly DateTime: string;
        readonly TunnelID: string;
        readonly ServiceID: string;
        readonly ConnectorID: string;
        readonly TokenID: string;
        /** @description 与 Audit ADMIN actor_id 相同。 */
        readonly AdminID: string;
        readonly EventID: string;
        readonly OperationID: string;
        readonly RequestID: string;
        readonly LoginRequest: {
            readonly username: string;
            readonly password: $Write<string>;
        };
        readonly Admin: {
            readonly id: components["schemas"]["AdminID"];
            readonly username: string;
        };
        readonly AuthSession: {
            readonly admin: components["schemas"]["Admin"];
            /** @description 32-byte 无 padding base64url Token。 */
            readonly csrf_token: string;
            readonly expires_at: components["schemas"]["DateTime"];
        };
        /** @enum {string} */
        readonly TunnelStatus: "PENDING" | "ONLINE" | "DEGRADED" | "OFFLINE" | "REVOKED";
        readonly Tunnel: {
            readonly id: components["schemas"]["TunnelID"];
            readonly name: string;
            /** Format: int64 */
            readonly version: number;
            /** Format: int64 */
            readonly desired_revision: number;
            readonly status: components["schemas"]["TunnelStatus"];
            readonly connectors_online: number;
            readonly services_count: number;
            readonly active_connections: number;
            readonly last_seen_at: components["schemas"]["DateTime"] | null;
            readonly first_authenticated_at: components["schemas"]["DateTime"] | null;
            readonly revoked_at: components["schemas"]["DateTime"] | null;
            readonly created_at: components["schemas"]["DateTime"];
            readonly updated_at: components["schemas"]["DateTime"];
        } & (unknown & unknown & unknown);
        readonly CreateTunnelRequest: {
            readonly name: string;
        };
        readonly UpdateTunnelRequest: {
            readonly name?: string;
        };
        readonly TunnelList: {
            readonly items: readonly components["schemas"]["Tunnel"][];
            readonly next_page_token?: string;
        };
        /** @enum {string} */
        readonly ConnectorStatus: "ONLINE" | "DEGRADED" | "DRAINING";
        readonly Connector: {
            readonly id: components["schemas"]["ConnectorID"];
            readonly tunnel_id: components["schemas"]["TunnelID"];
            readonly hostname: string;
            readonly os: string;
            readonly arch: string;
            readonly version: string;
            readonly status: components["schemas"]["ConnectorStatus"];
            readonly idle_work_connections: number;
            readonly active_connections: number;
            readonly connected_at: components["schemas"]["DateTime"];
            readonly last_heartbeat_at: components["schemas"]["DateTime"];
            readonly config_ready: boolean;
            /** Format: int64 */
            readonly observed_revision: number;
        };
        readonly ConnectorList: {
            readonly items: readonly components["schemas"]["Connector"][];
            readonly next_page_token?: string;
        };
        readonly ConnectionCredentialMetadata: {
            readonly tunnel_id: components["schemas"]["TunnelID"];
            readonly token_id: components["schemas"]["TokenID"];
            /** Format: int64 */
            readonly token_version: number;
            /** @enum {string} */
            readonly status: "ACTIVE" | "REVOKED_FOR_NEW_SESSION" | "REVOKED";
        };
        readonly DeploymentCommand: {
            /** @enum {string} */
            readonly environment: "FOREGROUND" | "CONTAINER" | "LINUX_SYSTEMD" | "WINDOWS_SCM";
            /** @description 一次性展示，可能包含完整 Token。 */
            readonly command: string;
        };
        readonly ConnectionCredential: {
            readonly tunnel_id: components["schemas"]["TunnelID"];
            readonly token_id: components["schemas"]["TokenID"];
            /** Format: int64 */
            readonly token_version: number;
            /** @constant */
            readonly status: "ACTIVE";
            readonly connection_token: string;
            readonly deployment_commands: readonly components["schemas"]["DeploymentCommand"][];
        };
        readonly TunnelCredentialResponse: {
            readonly tunnel: components["schemas"]["Tunnel"];
            readonly credential: components["schemas"]["ConnectionCredential"];
        };
        readonly Origin: components["schemas"]["HTTPOrigin"] | components["schemas"]["HTTPSOrigin"] | components["schemas"]["TCPOrigin"];
        readonly HTTPOrigin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "http";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
            readonly http_host_header?: string;
        };
        readonly HTTPSOrigin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "https";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
            /** @default true */
            readonly tls_verify: boolean;
            readonly tls_server_name?: string;
            readonly http_host_header?: string;
        };
        readonly TCPOrigin: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "tcp";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
        };
        readonly OriginInput: components["schemas"]["HTTPOriginInput"] | components["schemas"]["HTTPSOriginInput"] | components["schemas"]["TCPOriginInput"];
        readonly HTTPOriginInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "http";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
            readonly http_host_header?: string;
        };
        readonly HTTPSOriginInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "https";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
            /** @default true */
            readonly tls_verify: boolean;
            readonly tls_server_name?: string;
            readonly http_host_header?: string;
        };
        readonly TCPOriginInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly scheme: "tcp";
            readonly host: string;
            readonly port: number;
            /** @default 5000 */
            readonly connect_timeout_ms: number;
        };
        /** @description 字段与有效 scheme 的适用性按 Origin 联合类型校验。 */
        readonly OriginPatch: {
            /** @enum {string} */
            readonly scheme?: "http" | "https" | "tcp";
            readonly host?: string;
            readonly port?: number;
            readonly connect_timeout_ms?: number;
            readonly tls_verify?: boolean;
            readonly tls_server_name?: string;
            readonly http_host_header?: string;
        };
        readonly ProxyOptions: components["schemas"]["HTTPProxyOptions"] | components["schemas"]["TCPProxyOptions"];
        readonly HTTPProxyOptions: {
            /** @default false */
            readonly disable_chunked_encoding: boolean;
            /** @default false */
            readonly disable_happy_eyeballs: boolean;
            /** @default 90000 */
            readonly http_idle_connection_timeout_ms: number;
            /** @default 100 */
            readonly http_max_idle_connections: number;
            /** @default 30000 */
            readonly tcp_keepalive_interval_ms: number;
        };
        readonly TCPProxyOptions: {
            /** @default false */
            readonly disable_happy_eyeballs: boolean;
            /** @default 30000 */
            readonly tcp_keepalive_interval_ms: number;
        };
        readonly ProxyOptionsPatch: {
            readonly disable_chunked_encoding?: boolean;
            readonly disable_happy_eyeballs?: boolean;
            readonly http_idle_connection_timeout_ms?: number;
            readonly http_max_idle_connections?: number;
            readonly tcp_keepalive_interval_ms?: number;
        };
        /** @description 省略字段使用机器契约中的 V0.1 默认值；HTTP 专属字段用于 TCP 时拒绝。 */
        readonly ProxyOptionsInput: {
            /** @default false */
            readonly disable_chunked_encoding: boolean;
            /** @default false */
            readonly disable_happy_eyeballs: boolean;
            /** @default 90000 */
            readonly http_idle_connection_timeout_ms: number;
            /** @default 100 */
            readonly http_max_idle_connections: number;
            /** @default 30000 */
            readonly tcp_keepalive_interval_ms: number;
        };
        readonly HealthCheck: components["schemas"]["TCPHealthCheck"] | components["schemas"]["HTTPHealthCheck"];
        readonly TCPHealthCheck: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "TCP";
            /** @default 10000 */
            readonly interval_ms: number;
            /**
             * @description 必须小于 interval_ms。
             * @default 2000
             */
            readonly timeout_ms: number;
            /** @default 3 */
            readonly failure_threshold: number;
            /** @default 2 */
            readonly success_threshold: number;
        };
        readonly HTTPHealthCheck: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "HTTP";
            /** @default /health */
            readonly path: string;
            /** @default 10000 */
            readonly interval_ms: number;
            /**
             * @description 必须小于 interval_ms。
             * @default 2000
             */
            readonly timeout_ms: number;
            /** @default 200 */
            readonly expected_status_min: number;
            /** @default 399 */
            readonly expected_status_max: number;
            /** @default 3 */
            readonly failure_threshold: number;
            /** @default 2 */
            readonly success_threshold: number;
        };
        readonly HealthCheckPatch: {
            /** @enum {string} */
            readonly type?: "TCP" | "HTTP";
            readonly path?: string;
            readonly interval_ms?: number;
            readonly timeout_ms?: number;
            readonly expected_status_min?: number;
            readonly expected_status_max?: number;
            readonly failure_threshold?: number;
            readonly success_threshold?: number;
        };
        readonly HealthCheckInput: components["schemas"]["TCPHealthCheckInput"] | components["schemas"]["HTTPHealthCheckInput"];
        readonly TCPHealthCheckInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "TCP";
            /** @default 10000 */
            readonly interval_ms: number;
            /** @default 2000 */
            readonly timeout_ms: number;
            /** @default 3 */
            readonly failure_threshold: number;
            /** @default 2 */
            readonly success_threshold: number;
        };
        readonly HTTPHealthCheckInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "HTTP";
            /** @default /health */
            readonly path: string;
            /** @default 10000 */
            readonly interval_ms: number;
            /** @default 2000 */
            readonly timeout_ms: number;
            /** @default 200 */
            readonly expected_status_min: number;
            /** @default 399 */
            readonly expected_status_max: number;
            /** @default 3 */
            readonly failure_threshold: number;
            /** @default 2 */
            readonly success_threshold: number;
        };
        readonly Exposure: components["schemas"]["HTTPExposure"] | components["schemas"]["TCPExposure"];
        readonly HTTPExposure: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "http";
            readonly hostname: string;
            /** @default / */
            readonly path_prefix: string;
            /** @default true */
            readonly preserve_host: boolean;
        };
        readonly TCPExposure: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "tcp";
            readonly public_port: number;
        };
        /** @description 字段与有效 type 的适用性按 Exposure 联合类型校验。 */
        readonly ExposurePatch: {
            /** @enum {string} */
            readonly type?: "http" | "tcp";
            readonly hostname?: string;
            readonly path_prefix?: string;
            readonly preserve_host?: boolean;
            readonly public_port?: number;
        };
        readonly ExposureInput: components["schemas"]["HTTPExposureInput"] | components["schemas"]["TCPExposureInput"];
        readonly HTTPExposureInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "http";
            readonly hostname: string;
            /** @default / */
            readonly path_prefix: string;
            /** @default true */
            readonly preserve_host: boolean;
        };
        readonly TCPExposureInput: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "tcp";
            /** @description 省略时由 Server 从配置端口池原子分配。 */
            readonly public_port?: number;
        };
        /** @enum {string} */
        readonly ServiceStatus: "DISABLED" | "APPLY_FAILED" | "TUNNEL_OFFLINE" | "CONFIG_SYNCING" | "ORIGIN_UNHEALTHY" | "NO_CAPACITY" | "READY";
        readonly ApplyFailure: {
            readonly error_code: string;
            readonly failed_at: components["schemas"]["DateTime"];
        };
        /** @description M6 未就绪时返回 UNAVAILABLE，三个计数器都返回 null，不能伪造为 0。 */
        readonly UsageSummary: {
            /** @enum {string} */
            readonly availability: "AVAILABLE" | "UNAVAILABLE";
            /** Format: int64 */
            readonly connections_today: number | null;
            /** Format: int64 */
            readonly ingress_bytes_today: number | null;
            /** Format: int64 */
            readonly egress_bytes_today: number | null;
        };
        readonly Service: {
            readonly id: components["schemas"]["ServiceID"];
            readonly tunnel_id: components["schemas"]["TunnelID"];
            readonly name: string;
            /** Format: int64 */
            readonly required_revision: number;
            readonly origin: components["schemas"]["Origin"];
            readonly proxy_options: components["schemas"]["ProxyOptions"];
            readonly health: components["schemas"]["HealthCheck"] | null;
            readonly exposure: components["schemas"]["Exposure"] | null;
            readonly enabled: boolean;
            /** Format: int64 */
            readonly version: number;
            readonly status: components["schemas"]["ServiceStatus"];
            readonly apply_failure: components["schemas"]["ApplyFailure"] | null;
            readonly healthy_connectors: number;
            readonly active_connections: number;
            readonly usage: components["schemas"]["UsageSummary"];
            readonly created_at: components["schemas"]["DateTime"];
            readonly updated_at: components["schemas"]["DateTime"];
        } & (unknown & unknown);
        readonly CreateServiceRequest: {
            readonly tunnel_id: components["schemas"]["TunnelID"];
            readonly name: string;
            readonly origin: components["schemas"]["OriginInput"];
            readonly proxy_options?: components["schemas"]["ProxyOptionsInput"];
            /** @default null */
            readonly health: components["schemas"]["HealthCheckInput"] | null;
            readonly exposure: components["schemas"]["ExposureInput"];
            /** @default true */
            readonly enabled: boolean;
        };
        readonly UpdateServiceRequest: {
            readonly name?: string;
            readonly origin?: components["schemas"]["OriginPatch"];
            readonly proxy_options?: components["schemas"]["ProxyOptionsPatch"];
            readonly health?: components["schemas"]["HealthCheckPatch"] | null;
            readonly exposure?: components["schemas"]["ExposurePatch"] | null;
        };
        readonly ServiceList: {
            readonly items: readonly components["schemas"]["Service"][];
            readonly next_page_token?: string;
        };
        readonly DashboardCounts: {
            readonly tunnels_total: number;
            readonly tunnels_online: number;
            readonly tunnels_offline: number;
            readonly connectors_online: number;
            readonly services_total: number;
            readonly services_ready: number;
            readonly services_error: number;
            readonly active_connections: number;
        };
        /** @description 由 Server 冻结的 Gateway 叶证书状态；客户端不得重算 level 或解析错误文本。 */
        readonly GatewayCertificate: {
            /** @enum {string} */
            readonly tls_mode: "public" | "pinned";
            readonly expires_at: components["schemas"]["DateTime"];
            /** Format: int64 */
            readonly remaining_seconds: number;
            /**
             * @description 分别表示剩余时间大于 30 天、不超过 30 天、不超过 7 天、不超过 1 天和已过期。
             * @enum {string}
             */
            readonly level: "HEALTHY" | "WARNING" | "CRITICAL" | "EMERGENCY" | "EXPIRED";
            readonly recent_renewal_failed: boolean;
            readonly recent_renewal_error_code: "GATEWAY_CERTIFICATE_RENEWAL_FAILED" | null;
        };
        readonly RecentError: {
            /**
             * @description M6-05 Dashboard 使用的五类冻结诊断码。
             * @enum {string}
             */
            readonly code: "TUNNEL_OFFLINE" | "CONNECTOR_OFFLINE" | "ORIGIN_DOWN" | "NO_CAPACITY" | "PROTOCOL_ERROR";
            readonly message: string;
            readonly occurred_at: components["schemas"]["DateTime"];
            readonly request_id?: components["schemas"]["RequestID"] | null;
        };
        /** @description M6-05 Error Read Model 就绪后返回 AVAILABLE；没有最近错误时 items 为空。UNAVAILABLE 只表示该 Read Model 尚不可用。 */
        readonly RecentErrorsSummary: {
            /** @enum {string} */
            readonly availability: "AVAILABLE" | "UNAVAILABLE";
            readonly items: readonly components["schemas"]["RecentError"][];
        };
        readonly Dashboard: {
            /** @enum {string} */
            readonly server_status: "READY" | "DEGRADED";
            readonly counts: components["schemas"]["DashboardCounts"];
            readonly traffic: components["schemas"]["UsageSummary"];
            readonly recent_errors: components["schemas"]["RecentErrorsSummary"];
            readonly gateway_certificate?: components["schemas"]["GatewayCertificate"];
            readonly generated_at: components["schemas"]["DateTime"];
        };
        readonly SystemInfo: {
            readonly version: string;
            readonly go_version: string;
            /** @constant */
            readonly protocol_version: "v1";
            readonly os: string;
            readonly arch: string;
            readonly started_at: components["schemas"]["DateTime"];
            /** Format: int64 */
            readonly uptime_seconds: number;
        };
        readonly HealthCheckResult: {
            readonly name: string;
            /** @enum {string} */
            readonly status: "READY" | "DEGRADED";
            readonly message?: string | null;
        };
        readonly SystemHealth: {
            /** @enum {string} */
            readonly status: "READY" | "DEGRADED";
            readonly checks: readonly components["schemas"]["HealthCheckResult"][];
            readonly checked_at: components["schemas"]["DateTime"];
        };
        readonly SystemConfig: {
            readonly management: {
                /** Format: uri */
                readonly public_url: string;
            };
            readonly agent_gateway: {
                readonly public_hostname: string;
                /** @enum {string} */
                readonly tls_mode: "public" | "pinned";
            };
            readonly tcp_ingress: {
                readonly min_port: number;
                readonly max_port: number;
            };
            readonly logging: {
                /** @enum {string} */
                readonly level: "debug" | "info" | "warn" | "error";
            };
            readonly limits: components["schemas"]["PublicLimits"];
            /** @constant */
            readonly changes_require_restart: true;
        };
        readonly PublicLimits: {
            readonly max_tunnels: number;
            readonly max_connectors: number;
            readonly max_connectors_per_tunnel: number;
            readonly max_services_per_tunnel: number;
            readonly max_active_connections: number;
            readonly max_connections_per_tunnel: number;
            readonly max_connections_per_service: number;
            readonly max_connections_per_source_ip: number;
            readonly max_open_rate_per_source_ip: number;
            readonly max_open_burst_per_source_ip: number;
            readonly max_http_requests_per_source_ip_per_second: number;
            readonly max_http_header_bytes: number;
            /** Format: int64 */
            readonly max_http_body_bytes: number;
        };
        /** @enum {string} */
        readonly SecurityAuditAction: "GATEWAY_KEY_ROTATE" | "CONNECTION_TOKEN_REVEAL" | "CONNECTION_TOKEN_ROTATE" | "CONNECTION_TOKEN_REVOKE" | "TUNNEL_REVOKE";
        /** @enum {string} */
        readonly SecurityAuditResult: "SUCCEEDED" | "FAILED";
        /** @enum {string} */
        readonly SecurityAuditResourceType: "GATEWAY_IDENTITY" | "TUNNEL_TOKEN" | "TUNNEL";
        readonly SecurityAuditEvent: {
            readonly event_id: components["schemas"]["EventID"];
            readonly operation_id: components["schemas"]["OperationID"];
            /** @constant */
            readonly event: "SECURITY_OPERATION_RESULT";
            readonly action: components["schemas"]["SecurityAuditAction"];
            /** @enum {string} */
            readonly actor_type: "LOCAL_OPERATOR" | "ADMIN";
            readonly actor_id: components["schemas"]["AdminID"] | null;
            readonly source_ip: string | null;
            readonly resource_type: components["schemas"]["SecurityAuditResourceType"];
            readonly resource_id: string;
            readonly result: components["schemas"]["SecurityAuditResult"];
            readonly error_code: string | null;
            readonly request_id: string | null;
            readonly trace_id: string | null;
            readonly before_state_digest: string | null;
            readonly after_state_digest: string | null;
            readonly occurred_at: components["schemas"]["DateTime"];
        } & (unknown & unknown & unknown & unknown & unknown & unknown & unknown);
        readonly SecurityAuditEventList: {
            readonly items: readonly components["schemas"]["SecurityAuditEvent"][];
            readonly next_page_token?: string;
        };
        readonly ErrorResponse: {
            readonly error: components["schemas"]["APIError"];
        };
        readonly SetupRequiredErrorResponse: {
            readonly error: components["schemas"]["APIError"] & {
                /** @constant */
                readonly code?: "SETUP_REQUIRED";
            };
        };
        readonly APIError: {
            readonly code: components["schemas"]["APIErrorCode"];
            readonly message: string;
            readonly request_id: components["schemas"]["RequestID"];
            readonly details?: components["schemas"]["FieldViolationsDetails"] | components["schemas"]["TunnelInUseDetails"] | components["schemas"]["SnapshotLimitDetails"] | components["schemas"]["ResourceVersionConflictDetails"];
        };
        /** @enum {string} */
        readonly APIErrorCode: "INVALID_REQUEST" | "INVALID_PAGE_TOKEN" | "INVALID_IF_MATCH" | "PRECONDITION_REQUIRED" | "VALIDATION_FAILED" | "AUTHENTICATION_FAILED" | "SESSION_EXPIRED" | "CSRF_INVALID" | "ORIGIN_NOT_ALLOWED" | "FORBIDDEN" | "RESOURCE_NOT_FOUND" | "RESOURCE_VERSION_CONFLICT" | "TUNNEL_IN_USE" | "TUNNEL_REVOKED" | "CONNECTION_TOKEN_UNAVAILABLE" | "ROUTE_CONFLICT" | "TCP_PORT_UNAVAILABLE" | "TUNNEL_SERVICE_LIMIT" | "SNAPSHOT_TOO_LARGE" | "RATE_LIMITED" | "SETUP_REQUIRED" | "RUNTIME_CONVERGENCE_FAILED" | "INTERNAL_ERROR";
        readonly FieldViolation: {
            readonly field: string;
            readonly reason: string;
        };
        readonly FieldViolationsDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "FIELD_VIOLATIONS";
            readonly violations: readonly components["schemas"]["FieldViolation"][];
        };
        readonly TunnelInUseDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "TUNNEL_IN_USE";
            /** Format: int64 */
            readonly service_count: number;
            readonly referencing_service_ids: readonly components["schemas"]["ServiceID"][];
            readonly references_truncated: boolean;
        };
        readonly SnapshotLimitDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "SNAPSHOT_LIMIT";
            readonly tunnel_id: components["schemas"]["TunnelID"];
            /** Format: int64 */
            readonly service_count: number;
            /** Format: int64 */
            readonly snapshot_bytes: number;
            /** Format: int64 */
            readonly configured_limit: number;
        };
        readonly ResourceVersionConflictDetails: {
            /**
             * @description discriminator enum property added by openapi-typescript
             * @enum {string}
             */
            readonly type: "RESOURCE_VERSION_CONFLICT";
            /** @enum {string} */
            readonly resource_type: "TUNNEL" | "SERVICE";
            readonly resource_id: components["schemas"]["TunnelID"] | components["schemas"]["ServiceID"];
            readonly current_etag: string;
        };
    };
    responses: {
        /** @description Tunnel 当前表示。 */
        readonly TunnelOK: {
            headers: {
                readonly ETag: components["headers"]["TunnelETag"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["Tunnel"];
            };
        };
        /** @description Service 当前表示。 */
        readonly ServiceOK: {
            headers: {
                readonly ETag: components["headers"]["ServiceETag"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["Service"];
            };
        };
        /** @description 当前 Token 与部署指引；同一 Token Version 内逐字节稳定。 */
        readonly SecretCredentialOK: {
            headers: {
                readonly "Cache-Control": components["headers"]["NoStore"];
                readonly Pragma: components["headers"]["NoCache"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ConnectionCredential"];
            };
        };
        /** @description 请求格式错误。 */
        readonly BadRequest: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 未认证、凭据错误或 Session 失效。 */
        readonly Unauthorized: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description Origin、CSRF 或权限校验失败。 */
        readonly Forbidden: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 资源不存在。 */
        readonly NotFound: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 领域不变量冲突。 */
        readonly Conflict: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 尚无管理员，必须先通过受支持的本机 Bootstrap 路径创建首个 Admin；错误码固定为 SETUP_REQUIRED。 */
        readonly SetupRequired: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["SetupRequiredErrorResponse"];
            };
        };
        /** @description ETag 与当前版本冲突。 */
        readonly PreconditionFailed: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 字段或容量校验失败。 */
        readonly ValidationFailed: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 缺少 If-Match。 */
        readonly PreconditionRequired: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 请求被限流。 */
        readonly RateLimited: {
            headers: {
                readonly "Retry-After": components["headers"]["RetryAfter"];
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
        /** @description 内部错误且不泄露实现细节。 */
        readonly InternalError: {
            headers: {
                readonly [name: string]: unknown;
            };
            content: {
                readonly "application/json": components["schemas"]["ErrorResponse"];
            };
        };
    };
    parameters: {
        /** @description 必须与规范化 Management Host 同源。 */
        readonly Origin: string;
        readonly TunnelID: components["schemas"]["TunnelID"];
        readonly ServiceID: components["schemas"]["ServiceID"];
        /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
        readonly IfMatch: string;
        readonly PageSize: number;
        /** @description 绑定资源、排序边界和 Filter Hash 的 Server 不透明 Token。 */
        readonly PageToken: string;
    };
    requestBodies: never;
    headers: {
        /** @description Tunnel Version 强 ETag，例如 `"7"`。 */
        readonly TunnelETag: string;
        /** @description 绑定 Service Version 与 Tunnel Version 的强不透明 ETag。 */
        readonly ServiceETag: string;
        /** @description Secret 响应禁止存储。 */
        readonly NoStore: "no-store";
        /** @description 兼容缓存禁止指令。 */
        readonly NoCache: "no-cache";
        /** @description xtunnel_admin_session；HTTPS 模式使用 Secure，本机 HTTP 模式不设置 Secure；HttpOnly、SameSite=Lax、Host-only、Path=/api/v1。 */
        readonly SessionCookie: string;
        /** @description 建议等待秒数。 */
        readonly RetryAfter: number;
        /** @description 新资源的同源 `/api/v1` 路径。 */
        readonly Location: string;
    };
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    readonly login: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["LoginRequest"];
            };
        };
        readonly responses: {
            /** @description 登录成功。 */
            readonly 200: {
                headers: {
                    readonly "Set-Cookie": components["headers"]["SessionCookie"];
                    readonly "Cache-Control": components["headers"]["NoStore"];
                    readonly Pragma: components["headers"]["NoCache"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthSession"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 409: components["responses"]["SetupRequired"];
            readonly 429: components["responses"]["RateLimited"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly logout: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Session 已销毁；响应不包含 Body。 */
            readonly 204: {
                headers: {
                    /** @description 清除 Session Cookie。 */
                    readonly "Set-Cookie"?: string;
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getCurrentAdmin: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 当前 Session。 */
            readonly 200: {
                headers: {
                    readonly "Cache-Control": components["headers"]["NoStore"];
                    readonly Pragma: components["headers"]["NoCache"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["AuthSession"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly listTunnels: {
        readonly parameters: {
            readonly query?: {
                readonly page_size?: components["parameters"]["PageSize"];
                /** @description 绑定资源、排序边界和 Filter Hash 的 Server 不透明 Token。 */
                readonly page_token?: components["parameters"]["PageToken"];
                readonly status?: components["schemas"]["TunnelStatus"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 按 id 升序；无后续页时省略 next_page_token。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TunnelList"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly createTunnel: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateTunnelRequest"];
            };
        };
        readonly responses: {
            /** @description Tunnel 与第一代 Token 已创建。 */
            readonly 201: {
                headers: {
                    readonly Location: components["headers"]["Location"];
                    readonly ETag: components["headers"]["TunnelETag"];
                    readonly "Cache-Control": components["headers"]["NoStore"];
                    readonly Pragma: components["headers"]["NoCache"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["TunnelCredentialResponse"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 409: components["responses"]["Conflict"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 429: components["responses"]["RateLimited"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getTunnel: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Tunnel 当前表示。 */
            readonly 200: {
                headers: {
                    readonly ETag: components["headers"]["TunnelETag"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Tunnel"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly deleteTunnel: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Tunnel 已删除；响应不包含 Body。 */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly updateTunnel: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/merge-patch+json": components["schemas"]["UpdateTunnelRequest"];
            };
        };
        readonly responses: {
            readonly 200: components["responses"]["TunnelOK"];
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly listTunnelConnectors: {
        readonly parameters: {
            readonly query?: {
                readonly page_size?: components["parameters"]["PageSize"];
                /** @description 绑定资源、排序边界和 Filter Hash 的 Server 不透明 Token。 */
                readonly page_token?: components["parameters"]["PageToken"];
                readonly status?: components["schemas"]["ConnectorStatus"];
            };
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 按 connector_id 升序。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConnectorList"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly revealTunnelToken: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["SecretCredentialOK"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly rotateTunnelToken: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 新 Token。 */
            readonly 200: {
                headers: {
                    readonly ETag: components["headers"]["TunnelETag"];
                    readonly "Cache-Control": components["headers"]["NoStore"];
                    readonly Pragma: components["headers"]["NoCache"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConnectionCredential"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly revokeTunnelToken: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 已撤销的 Token 元数据；永不返回 Token 文本。 */
            readonly 200: {
                headers: {
                    readonly ETag: components["headers"]["TunnelETag"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ConnectionCredentialMetadata"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly revokeTunnel: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly tunnel_id: components["parameters"]["TunnelID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["TunnelOK"];
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly listServices: {
        readonly parameters: {
            readonly query: {
                readonly tunnel_id: components["schemas"]["TunnelID"];
                readonly page_size?: components["parameters"]["PageSize"];
                /** @description 绑定资源、排序边界和 Filter Hash 的 Server 不透明 Token。 */
                readonly page_token?: components["parameters"]["PageToken"];
                readonly status?: components["schemas"]["ServiceStatus"];
                readonly enabled?: boolean;
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 按 id 升序。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["ServiceList"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly createService: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/json": components["schemas"]["CreateServiceRequest"];
            };
        };
        readonly responses: {
            /** @description Service 已创建；ETag 绑定 Service 与 Tunnel 版本。 */
            readonly 201: {
                headers: {
                    readonly Location: components["headers"]["Location"];
                    readonly ETag: components["headers"]["ServiceETag"];
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Service"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getService: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["ServiceOK"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 404: components["responses"]["NotFound"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly deleteService: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Service 已删除；响应不包含 Body。 */
            readonly 204: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content?: never;
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly updateService: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody: {
            readonly content: {
                readonly "application/merge-patch+json": components["schemas"]["UpdateServiceRequest"];
            };
        };
        readonly responses: {
            readonly 200: components["responses"]["ServiceOK"];
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly enableService: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["ServiceOK"];
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly disableService: {
        readonly parameters: {
            readonly query?: never;
            readonly header: {
                /** @description 必须与规范化 Management Host 同源。 */
                readonly Origin: components["parameters"]["Origin"];
                /** @description 单个精确强 ETag；不接受 *、弱 ETag 或多值。 */
                readonly "If-Match": components["parameters"]["IfMatch"];
            };
            readonly path: {
                readonly service_id: components["parameters"]["ServiceID"];
            };
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            readonly 200: components["responses"]["ServiceOK"];
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 403: components["responses"]["Forbidden"];
            readonly 404: components["responses"]["NotFound"];
            readonly 409: components["responses"]["Conflict"];
            readonly 412: components["responses"]["PreconditionFailed"];
            readonly 422: components["responses"]["ValidationFailed"];
            readonly 428: components["responses"]["PreconditionRequired"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getDashboard: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Dashboard 快照；客户端不得重算状态。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["Dashboard"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getSystemInfo: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Server 信息。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SystemInfo"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getSystemHealth: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 管理面健康状态。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SystemHealth"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly getSystemConfig: {
        readonly parameters: {
            readonly query?: never;
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description 只读安全配置投影。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SystemConfig"];
                };
            };
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly listSecurityAuditEvents: {
        readonly parameters: {
            readonly query?: {
                readonly page_size?: components["parameters"]["PageSize"];
                /** @description 绑定资源、排序边界和 Filter Hash 的 Server 不透明 Token。 */
                readonly page_token?: components["parameters"]["PageToken"];
                readonly action?: components["schemas"]["SecurityAuditAction"];
                readonly result?: components["schemas"]["SecurityAuditResult"];
                readonly resource_type?: components["schemas"]["SecurityAuditResourceType"];
                readonly resource_id?: string;
                /** @description 包含此 UTC 时刻。 */
                readonly occurred_from?: components["schemas"]["DateTime"];
                /** @description 不包含此 UTC 时刻。 */
                readonly occurred_to?: components["schemas"]["DateTime"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description Security Audit Event 列表。 */
            readonly 200: {
                headers: {
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/json": components["schemas"]["SecurityAuditEventList"];
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
    readonly exportSecurityAuditEvents: {
        readonly parameters: {
            readonly query?: {
                readonly action?: components["schemas"]["SecurityAuditAction"];
                readonly result?: components["schemas"]["SecurityAuditResult"];
                readonly resource_type?: components["schemas"]["SecurityAuditResourceType"];
                readonly resource_id?: string;
                /** @description 包含此 UTC 时刻。 */
                readonly occurred_from?: components["schemas"]["DateTime"];
                /** @description 不包含此 UTC 时刻。 */
                readonly occurred_to?: components["schemas"]["DateTime"];
            };
            readonly header?: never;
            readonly path?: never;
            readonly cookie?: never;
        };
        readonly requestBody?: never;
        readonly responses: {
            /** @description NDJSON 流；每行是一个 SecurityAuditEvent，空结果返回空 Body。 */
            readonly 200: {
                headers: {
                    readonly "Cache-Control": components["headers"]["NoStore"];
                    readonly "Content-Disposition": "attachment; filename=\"xtunnel-security-audit.ndjson\"";
                    readonly [name: string]: unknown;
                };
                content: {
                    readonly "application/x-ndjson": string;
                };
            };
            readonly 400: components["responses"]["BadRequest"];
            readonly 401: components["responses"]["Unauthorized"];
            readonly 500: components["responses"]["InternalError"];
        };
    };
}
